import { ComponentOption } from './types.js';

export const SHADCN_COMPONENTS: ComponentOption[] = [
  { name: 'Accordion', value: 'accordion', description: 'Collapsible content sections' },
  { name: 'Alert', value: 'alert', description: 'Important messages and notifications' },
  { name: 'Alert Dialog', value: 'alert-dialog', description: 'Modal dialogs for important actions' },
  { name: 'Aspect Ratio', value: 'aspect-ratio', description: 'Maintain responsive aspect ratios' },
  { name: 'Avatar', value: 'avatar', description: 'User profile images' },
  { name: 'Badge', value: 'badge', description: 'Small status indicators' },
  { name: 'Breadcrumb', value: 'breadcrumb', description: 'Navigation breadcrumbs' },
  { name: 'Button', value: 'button', description: 'Interactive buttons with variants' },
  { name: 'Calendar', value: 'calendar', description: 'Date selection component' },
  { name: 'Card', value: 'card', description: 'Content containers with headers' },
  { name: 'Carousel', value: 'carousel', description: 'Image or content slideshows' },
  { name: 'Chart', value: 'chart', description: 'Data visualization charts' },
  { name: 'Checkbox', value: 'checkbox', description: 'Boolean input controls' },
  { name: 'Collapsible', value: 'collapsible', description: 'Expandable content sections' },
  { name: 'Command', value: 'command', description: 'Command palette interface' },
  { name: 'Context Menu', value: 'context-menu', description: 'Right-click context menus' },
  { name: 'Dialog', value: 'dialog', description: 'Modal overlay dialogs' },
  { name: 'Drawer', value: 'drawer', description: 'Slide-out side panels' },
  { name: 'Dropdown Menu', value: 'dropdown-menu', description: 'Toggleable menu lists' },
  { name: 'React Hook Form', value: 'form', description: 'Form validation and handling' },
  { name: 'Hover Card', value: 'hover-card', description: 'Rich preview cards' },
  { name: 'Input', value: 'input', description: 'Text input fields' },
  { name: 'Input OTP', value: 'input-otp', description: 'One-time password input' },
  { name: 'Label', value: 'label', description: 'Form field labels' },
  { name: 'Menubar', value: 'menubar', description: 'Horizontal navigation menus' },
  { name: 'Navigation Menu', value: 'navigation-menu', description: 'Multi-level navigation' },
  { name: 'Pagination', value: 'pagination', description: 'Page navigation controls' },
  { name: 'Popover', value: 'popover', description: 'Floating content containers' },
  { name: 'Progress', value: 'progress', description: 'Loading and progress indicators' },
  { name: 'Radio Group', value: 'radio-group', description: 'Single selection controls' },
  { name: 'Resizable', value: 'resizable', description: 'Resizable panels and layouts' },
  { name: 'Scroll Area', value: 'scroll-area', description: 'Custom scrollable areas' },
  { name: 'Select', value: 'select', description: 'Dropdown selection controls' },
  { name: 'Separator', value: 'separator', description: 'Visual content dividers' },
  { name: 'Sheet', value: 'sheet', description: 'Slide-out panels' },
  { name: 'Sidebar', value: 'sidebar', description: 'Sidebar navigation component' },
  { name: 'Skeleton', value: 'skeleton', description: 'Loading placeholders' },
  { name: 'Slider', value: 'slider', description: 'Range input controls' },
  { name: 'Sonner', value: 'sonner', description: 'Toast notifications' },
  { name: 'Switch', value: 'switch', description: 'Toggle switch controls' },
  { name: 'Table', value: 'table', description: 'Data table components' },
  { name: 'Tabs', value: 'tabs', description: 'Tabbed content sections' },
  { name: 'Textarea', value: 'textarea', description: 'Multi-line text inputs' },
  { name: 'Toggle', value: 'toggle', description: 'Toggle button controls' },
  { name: 'Toggle Group', value: 'toggle-group', description: 'Grouped toggle buttons' },
  { name: 'Tooltip', value: 'tooltip', description: 'Hover information displays' }
];

export const CONFIG_FILE_NAME = 'orbit.config.json';
export const DEFAULT_SHADCN_VERSION = 'latest'; 